/*
 * GLAD - OpenGL Loader
 *
 * This is a single-header OpenGL loader generated by https://glad.dav1d.de
 *
 * Profile: Core
 * API: OpenGL 3.3
 * Extensions: None
 *
 * TODO: Generate actual GLAD loader for production use:
 *   1. Go to https://glad.dav1d.de
 *   2. Select: Language=C/C++, Specification=OpenGL, gl=Version 3.3,
 * Profile=Core
 *   3. Check "Generate a loader"
 *   4. Download and extract glad.h and glad.c
 *
 * For now, we use a minimal stub that will work with the system's GL headers.
 */

#ifndef GLAD_H
#define GLAD_H

#ifdef __cplusplus
extern "C" {
#endif

// Include GL headers provided by the system
#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>

// Function pointer type for loading GL functions
typedef void *(*GLADloadproc)(const char *name);

// Stub loader function - GLAD normally generates this
int gladLoadGLLoader(GLADloadproc load);

#ifdef __cplusplus
}
#endif

#endif // GLAD_H
